# Generated by Django 4.0.3 on 2022-03-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(default='', editable=False, upload_to='thumbs'),
            preserve_default=False,
        ),
    ]
