# Generated by Django 4.0.3 on 2022-03-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_delete_photogallery'),
        ('picture', '0002_picture_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery'),
        ),
    ]
