# Generated by Django 4.0.3 on 2022-03-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_picture_thumbnail'),
        ('picture', '0003_alter_picture_gallery'),
    ]

    operations = [
    ]
