# Generated by Django 4.0.3 on 2022-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallery_slug'),
        ('picture', '0004_merge_20220330_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='gallery',
        ),
        migrations.AddField(
            model_name='picture',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, to='gallery.gallery'),
        ),
    ]
