# Generated by Django 4.0.3 on 2022-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallery_slug'),
        ('picture', '0005_remove_picture_gallery_picture_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='gallery.gallery'),
        ),
    ]
