# Generated by Django 3.2.8 on 2022-04-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_alter_picturescontainer_user'),
        ('picture', '0007_picture_is_public'),
    ]

    operations = [
    ]
