# Generated by Django 4.0.3 on 2022-04-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_alter_picturescontainer_user'),
        ('picture', '0007_picture_is_public'),
    ]

    operations = [
    ]
