# Generated by Django 4.0.3 on 2022-04-06 09:52

from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_merge_20220405_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=picture.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to=picture.models.get_thumb_upload_path),
        ),
    ]
