# Generated by Django 4.0.3 on 2022-04-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_merge_20220406_0603'),
        ('picture', '0009_alter_picture_image_alter_picture_thumbnail'),
    ]

    operations = [
    ]
