# Generated by Django 4.0.3 on 2022-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0010_merge_20220406_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
