# Generated by Django 4.0.3 on 2022-04-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0010_merge_20220406_1028'),
        ('picture', '0010_merge_20220406_1541'),
    ]

    operations = [
    ]
