# Generated by Django 4.0.3 on 2022-04-07 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0011_merge_20220407_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='is_public',
            new_name='public_link',
        ),
        migrations.AddField(
            model_name='picture',
            name='public_picture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
