# Generated by Django 4.0.3 on 2022-04-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0011_picture_description'),
        ('picture', '0012_rename_is_public_picture_public_link_and_more'),
    ]

    operations = [
    ]
