# Generated by Django 4.0.3 on 2022-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0016_picture_latitude_picture_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
