# Generated by Django 4.0.3 on 2022-04-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0017_picture_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturescontainer',
            old_name='created',
            new_name='uploaded_on',
        ),
    ]
