# Generated by Django 4.0.3 on 2022-04-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0013_merge_20220407_1840'),
        ('picture', '0019_remove_picture_latitude_remove_picture_longitude_and_more'),
    ]

    operations = [
    ]
