# Generated by Django 3.2.9 on 2022-04-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0020_merge_20220412_1529'),
        ('picture', '0020_merge_20220412_1535'),
    ]

    operations = [
    ]
