# Generated by Django 4.0.3 on 2022-04-13 16:24

from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0021_merge_20220413_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=picture.models.get_image_upload_path),
        ),
    ]
