# Generated by Django 4.0.3 on 2022-03-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photogallery",
            options={
                "verbose_name": "photo gallery",
                "verbose_name_plural": "photo galleries",
            },
        ),
    ]
