# Generated by Django 4.0.3 on 2022-03-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_photogallery_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhotoGallery",
        ),
    ]
