# Generated by Django 4.0.3 on 2022-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_delete_photogallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
