# Generated by Django 4.0.3 on 2022-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_gallery_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
